import '../models/color_entry.dart';
import '../models/palette.dart';

class PaletteCptCodec {
  static const String _generatedCommentHeader =
      '#Generated by ColorManager\n#Author Alsophila Chr0n0s';

  const PaletteCptCodec();

  List<int> encodeBytes(Palette palette) {
    final colors = palette.colors;
    if (colors.isEmpty) {
      return '# COLOR_MODEL = RGB\n$_generatedCommentHeader\n'.codeUnits;
    }

    final buffer = StringBuffer()
      ..writeln('# COLOR_MODEL = RGB')
      ..writeln(_generatedCommentHeader);

    if (colors.length == 1) {
      final rgb = colors.first.rgb;
      buffer.writeln(
        '0 ${rgb[0]} ${rgb[1]} ${rgb[2]} 1 ${rgb[0]} ${rgb[1]} ${rgb[2]}',
      );
    } else {
      for (var i = 0; i < colors.length - 1; i++) {
        final left = colors[i].rgb;
        final right = colors[i + 1].rgb;
        buffer.writeln(
          '$i ${left[0]} ${left[1]} ${left[2]} ${i + 1} ${right[0]} ${right[1]} ${right[2]}',
        );
      }
    }

    final first = colors.first.rgb;
    final last = colors.last.rgb;
    buffer
      ..writeln('B ${first[0]} ${first[1]} ${first[2]}')
      ..writeln('F ${last[0]} ${last[1]} ${last[2]}')
      ..writeln('N 128 128 128');

    return buffer.toString().codeUnits;
  }

  Palette decodeBytes(
    List<int> bytes, {
    required String fallbackName,
    String? sourcePath,
    String sourceGroup = 'materials',
  }) {
    final content = String.fromCharCodes(bytes);
    final lines = content.split(RegExp(r'\r?\n'));
    final colors = <ColorEntry>[];

    for (final raw in lines) {
      final line = raw.trim();
      if (line.isEmpty || line.startsWith('#')) {
        continue;
      }
      if (line.startsWith('B ') ||
          line.startsWith('F ') ||
          line.startsWith('N ')) {
        continue;
      }

      final parts = line.split(RegExp(r'\s+'));
      if (parts.length < 8) {
        continue;
      }

      final r = int.tryParse(parts[1]);
      final g = int.tryParse(parts[2]);
      final b = int.tryParse(parts[3]);
      if (r == null || g == null || b == null) {
        continue;
      }

      colors.add(
        ColorEntry(
          name: 'CPT ${colors.length + 1}',
          hexCode:
              '#${r.toRadixString(16).padLeft(2, '0').toUpperCase()}${g.toRadixString(16).padLeft(2, '0').toUpperCase()}${b.toRadixString(16).padLeft(2, '0').toUpperCase()}',
        ),
      );
    }

    return Palette(
      name: fallbackName,
      colors: colors,
      sourcePath: sourcePath,
      sourceFormat: 'cpt',
      sourceGroup: sourceGroup,
    );
  }
}
