import 'dart:convert';

import '../models/palette.dart';
import 'palette_ase_codec.dart';
import 'palette_cpt_codec.dart';
import 'palette_csv_codec.dart';
import 'palette_gpl_codec.dart';
import 'palette_json_codec.dart';
import 'palette_pal_codec.dart';

class PaletteCodecRouter {
  PaletteCodecRouter({
    PaletteAseCodec? ase,
    PaletteCsvCodec? csv,
    PaletteCptCodec? cpt,
    PaletteGplCodec? gpl,
    PaletteJsonCodec? json,
    PalettePalCodec? pal,
  })  : _ase = ase ?? const PaletteAseCodec(),
        _csv = csv ?? const PaletteCsvCodec(),
        _cpt = cpt ?? const PaletteCptCodec(),
        _gpl = gpl ?? const PaletteGplCodec(),
        _json = json ?? const PaletteJsonCodec(),
        _pal = pal ?? const PalettePalCodec();

  final PaletteAseCodec _ase;
  final PaletteCsvCodec _csv;
  final PaletteCptCodec _cpt;
  final PaletteGplCodec _gpl;
  final PaletteJsonCodec _json;
  final PalettePalCodec _pal;

  Palette decode({
    required String extension,
    required List<int> bytes,
    required String fallbackName,
    String? sourcePath,
    String sourceGroup = 'materials',
  }) {
    final normalized = _normalizeExtension(extension);
    switch (normalized) {
      case '.json':
        return _json.decodeBytes(
          bytes,
          fallbackName: fallbackName,
          sourcePath: sourcePath,
          sourceGroup: sourceGroup,
        );
      case '.csv':
        return _csv.decodeBytes(
          bytes,
          fallbackName: fallbackName,
          sourcePath: sourcePath,
          sourceGroup: sourceGroup,
        );
      case '.gpl':
        return _gpl.decodeBytes(
          bytes,
          fallbackName: fallbackName,
          sourcePath: sourcePath,
          sourceGroup: sourceGroup,
        );
      case '.cpt':
        return _cpt.decodeBytes(
          bytes,
          fallbackName: fallbackName,
          sourcePath: sourcePath,
          sourceGroup: sourceGroup,
        );
      case '.ase':
        return _ase.decodeBytes(
          bytes,
          fallbackName: fallbackName,
          sourcePath: sourcePath,
          sourceGroup: sourceGroup,
        );
      case '.pal':
        return _pal.decodeBytes(
          bytes,
          fallbackName: fallbackName,
          sourcePath: sourcePath,
          sourceGroup: sourceGroup,
        );
      default:
        throw FormatException('Unsupported file type: $extension');
    }
  }

  List<int> encode({
    required String extension,
    required Palette palette,
  }) {
    final normalized = _normalizeExtension(extension);
    switch (normalized) {
      case '.json':
        return _json.encodeBytes(palette, pretty: true, ensureAscii: true);
      case '.csv':
        return _csv.encodeBytes(palette);
      case '.gpl':
        return _gpl.encodeBytes(palette);
      case '.cpt':
        return _cpt.encodeBytes(palette);
      case '.ase':
        return _ase.encodeBytes(palette);
      case '.pal':
        return _pal.encodeOriginLabBytes(palette);
      case '.r':
        return utf8.encode(_encodeRScript(palette));
      case '.py':
        return utf8.encode(_encodePythonScript(palette));
      case '.m':
        return utf8.encode(_encodeMatlabScript(palette));
      default:
        throw FormatException('Unsupported output file type: $extension');
    }
  }

  String _encodeRScript(Palette palette) {
    final variableName = _safeVariableName(palette.name);
    final hexArray = palette.colors
        .map((color) => '"${color.hexCode.toUpperCase()}"')
        .join(', ');
    final nameArray = palette.colors
        .map((color) => '"${color.name.replaceAll('"', '\\"')}"')
        .join(', ');

    return [
      '# Generated by ColorManager',
      '$variableName <- c($hexArray)',
      'names($variableName) <- c($nameArray)',
      '',
    ].join('\n');
  }

  String _encodePythonScript(Palette palette) {
    final variableName = _safeVariableName(palette.name);
    final listLiteral = palette.colors
        .map((color) => '"${color.hexCode.toUpperCase()}"')
        .join(', ');
    final dictLiteral = palette.colors
        .map((color) =>
            '    "${color.name.replaceAll('"', '\\"')}": "${color.hexCode.toUpperCase()}"')
        .join(',\n');

    return [
      '# Generated by ColorManager',
      '$variableName = [$listLiteral]',
      '${variableName}_named = {',
      dictLiteral,
      '}',
      '',
    ].join('\n');
  }

  String _encodeMatlabScript(Palette palette) {
    final variableName = _safeVariableName(palette.name);
    final rows = palette.colors.map((color) {
      final rgb = color.rgb;
      final r = (rgb[0] / 255).toStringAsFixed(6);
      final g = (rgb[1] / 255).toStringAsFixed(6);
      final b = (rgb[2] / 255).toStringAsFixed(6);
      return '    $r, $g, $b';
    }).join(';\n');

    final hexRows = palette.colors
        .map((color) => '    "${color.hexCode.toUpperCase()}"')
        .join('; ...\n');

    return [
      '% Generated by ColorManager',
      '$variableName = [',
      rows,
      '];',
      '${variableName}_hex = [ ...',
      hexRows,
      '];',
      '',
    ].join('\n');
  }

  String _safeVariableName(String value) {
    final cleaned = value
        .trim()
        .replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_')
        .replaceAll(RegExp(r'_+'), '_');
    final nonEmpty = cleaned.isEmpty ? 'palette' : cleaned;
    if (RegExp(r'^[0-9]').hasMatch(nonEmpty)) {
      return 'palette_$nonEmpty';
    }
    return nonEmpty;
  }

  String _normalizeExtension(String value) {
    final lower = value.trim().toLowerCase();
    return lower.startsWith('.') ? lower : '.$lower';
  }
}
